### PR TITLE
make optic token optional, only upload when token is set

### PR DESCRIPTION
**Pull request by Alexandre-Herve**

### CODE REVIEW

**Review by niclim — APPROVED** [review]
You'll also need to run `yarn build` to generate the build assets

We can also test this out before merging if you want to tag this branch with `v1.0.8` + update some repo to use the tag

**Comment by notnmeyer** [comment]
very meta, but looks like this reformats to 4 spaces of indentation. monorail and optic both use 2 for ts. i don't particularly care, just calling out that departure.

edit: oh, i see prettier is complaining. i love how unhelpful "[warn] Code style issues found in the above file. Forgot to run Prettier?" is.

**Comment by Alexandre-Herve** [comment]
Well my editor doesn't seem to follow the project config, and also I ran `yarn run format` but the ci still complains -_- `yarn lint` passes locally as well, investigating

**Comment by Alexandre-Herve** [comment]
Ok so since no `.prettierrc` or equivalent is defined in the project, prettier was looking at my `~/.prettierrc` config, which differs from the default prettier config used on the ci. I'm adding a `prettier` block in package.json

**Pull request merged**
